#pragma once

#define SERVO_DATA_QUEUE_LENGTH	 3
#define WIFI_DATA_QUEUE_LENGTH	 3
#define WIFI_DATA_QUEUE_SIZE	 20

#define BLE_SERVER_STACK_SIZE	 NIMBLE_HS_STACK_SIZE
#define SLEEP_CTRL_STACK_SIZE	 3000
#define SERVO_STACK_SIZE		 3000
#define BLINK_STACK_SIZE		 3000

#define BLE_SERVER_TASK_PRIORITY (configMAX_PRIORITIES - 4)
#define SLEEP_CTRL_TASK_PRIORITY 2
#define SERVO_TASK_PRIORITY		 3
#define BLINK_TASK_PRIORITY		 1

#define COMM_CORE				 0
#define APP_CORE				 1