#pragma once

#define SERVO_ON_ANGLE			60
#define SERVO_OFF_ANGLE			-60

#define TIME_TO_WAKEUP			19
#define TIME_TO_SLEEP			20

#define ACTIVE_PERIOD_START_HR	23
#define ACTIVE_PERIOD_START_MIN 30
#define ACTIVE_PERIOD_START_SEC 0
#define ACTIVE_PERIOD_END_HR	1
#define ACTIVE_PERIOD_END_MIN	30
#define ACTIVE_PERIOD_END_SEC	0

// todo: multiple period